### ISSUE TITLE
Call to undefined method TYPO3\CMS\Form\Domain\Model\FormDefinition::getElements()

### ISSUE THREAD

**Issue by robsonrobi** [TYPO3-Initiatives/headless#298]
Trying to use headlless with ext:form crashes. Is there any chance to get it working with the related nuxt example ?
Would be really great.

**Comment by twoldanski** [comment]
Hi @robsonrobi,
Could you provide more context? What TYPO3 & headless version are you using?
Also could you provide example form configuration causing crash?

**Comment by robsonrobi** [comment]
Hi @twoldanski : Yes of course. I am using typo3 9.5.30 and the latest headless version. I just creates a form with two simple input fields. The problem is in the code of headless, there is no method getElements in the FormDefintion.

https://github.com/TYPO3/typo3/blob/v9.5.30/typo3/sysext/form/Classes/Domain/Model/FormDefinition.php

I think you have to fetch them with 

```
 /** @var FormDefinition $definition */
        $definition = $formRuntime->getFormDefinition();
        $pages = $definition->getPages();

        /** @var Page $page */
        foreach ($pages as $page) {
            $elements = $page->getElements();
        }
```

But here the problem comes with multiple step forms. Using one step it may be work, but i receive further errors concerning missing Translation-Files, etc...

Is there a chance, that you can provide a working example with the contact.form.yaml and the corresponding nuxt project. It does not fit either, because this.form.renderables is null... I just followed the given example and that crashes using it with ext:form, the rest works.

I would love to replace the oldschool fluid html form with a vuejs framework and i liked your headless try.

Greetings
robsonrobi

**Comment by robsonrobi** [comment]
Here is a basic form yaml


```

renderingOptions:
  submitButtonLabel: Submit
type: Form
identifier: contact
label: contact
prototypeName: standard
renderables:
  -
    renderingOptions:
      previousButtonLabel: 'Previous step'
      nextButtonLabel: Next
    type: Page
    identifier: page-1
    label: 'Step 1'
    renderables:
      -
        defaultValue: ''
        type: Text
        identifier: text-1
        label: Name
        properties:
          fluidAdditionalAttributes:
            maxlength: '200'
            minlength: '2'
        validators:
          -
            options:
              minimum: '2'
              maximum: '200'
            identifier: StringLength
      -
        defaultValue: ''
        type: Email
        identifier: email-1
        label: E-Mail
        properties:
          fluidAdditionalAttributes:
            required: required
          validationErrorMessages:
            -
              code: 1221560910
              message: 'Bitte geben sie eine Email ein'
            -
              code: 1221560718
              message: 'Bitte geben sie eine Email ein'
            -
              code: 1347992400
              message: 'Bitte geben sie eine Email ein'
            -
              code: 1347992453
              message: 'Bitte geben sie eine Email ein'
            -
              code: 1221559976
              message: 'Error in Email'
        validators:
          -
            identifier: EmailAddress
          -
            identifier: NotEmpty
      -
        type: GridRow
        identifier: gridrow-1
        label: 'Grid: Row'
        renderables:
          -
            defaultValue: ''
            type: Text
            identifier: text-2
            label: Straße
          -
            defaultValue: ''
            type: Text
            identifier: text-3
            label: Nummer
  -
    renderingOptions:
      previousButtonLabel: 'Previous step'
      nextButtonLabel: 'Next step'
      stepFinishers:
        - CheckSave
    type: Page
    identifier: page-2
    label: 'Step 2'
    renderables:
      -
        defaultValue: ''
        type: Text
        identifier: text-4
        label: IBAN
  -
    renderingOptions:
      previousButtonLabel: 'Previous step'
      nextButtonLabel: 'Next step'
    type: SummaryPage
    identifier: summarypage-1
    label: 'Summary step'


```
